//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLY_MEMBER
    {
        public int ID { get; set; }
        public int MAP_APPLY_ID { get; set; }
        public int REF_ACT_ID { get; set; }
        public string MEMBER_IDEN_ID { get; set; }
        public string MERBER_NM { get; set; }
        public string MERBER_TP { get; set; }
        public string MEMBER_BIRDT { get; set; }
        public System.DateTime BUD_DT { get; set; }
        public System.DateTime UPD_DT { get; set; }
    }
}
