//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL
    {
        public int EMAIL_ID { get; set; }
        public string PUBLISHER { get; set; }
        public Nullable<System.DateTime> DELIEVER_DATE { get; set; }
        public string DELIEVER_TYPE { get; set; }
        public string TITLE { get; set; }
        public int STATUS { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_NAME { get; set; }
        public Nullable<int> SEND_NAME { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public int INSERT_NAME { get; set; }
        public string MAIL_FORM { get; set; }
        public string MAIL_SUBJECT { get; set; }
        public string MAIL_BODY { get; set; }
    }
}
