//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEnergy : DbContext
    {
        public DBEnergy()
            : base("name=DBEnergy")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMAIL> EMAIL { get; set; }
        public virtual DbSet<FAX> FAX { get; set; }
        public virtual DbSet<FAXDetail> FAXDetail { get; set; }
        public virtual DbSet<LOGERR> LOGERR { get; set; }
        public virtual DbSet<SiteCounter> SiteCounter { get; set; }
        public virtual DbSet<SMS> SMS { get; set; }
        public virtual DbSet<SMSDetail> SMSDetail { get; set; }
        public virtual DbSet<SMSResponseMsg> SMSResponseMsg { get; set; }
        public virtual DbSet<SystemLog> SystemLog { get; set; }
        public virtual DbSet<TempValidUser> TempValidUser { get; set; }
        public virtual DbSet<人員> 人員 { get; set; }
        public virtual DbSet<分類主檔> 分類主檔 { get; set; }
        public virtual DbSet<分類明細檔> 分類明細檔 { get; set; }
        public virtual DbSet<分類對應檔> 分類對應檔 { get; set; }
        public virtual DbSet<出版品主檔> 出版品主檔 { get; set; }
        public virtual DbSet<出版品章節明細檔> 出版品章節明細檔 { get; set; }
        public virtual DbSet<功能項目檔> 功能項目檔 { get; set; }
        public virtual DbSet<外部連結> 外部連結 { get; set; }
        public virtual DbSet<研討會主檔> 研討會主檔 { get; set; }
        public virtual DbSet<研討會報名主檔> 研討會報名主檔 { get; set; }
        public virtual DbSet<研討會報名對應檔> 研討會報名對應檔 { get; set; }
        public virtual DbSet<問卷主檔> 問卷主檔 { get; set; }
        public virtual DbSet<問卷答案主檔> 問卷答案主檔 { get; set; }
        public virtual DbSet<問卷答案明細檔> 問卷答案明細檔 { get; set; }
        public virtual DbSet<問卷選項檔> 問卷選項檔 { get; set; }
        public virtual DbSet<問卷題目檔> 問卷題目檔 { get; set; }
        public virtual DbSet<問卷題目類型檔> 問卷題目類型檔 { get; set; }
        public virtual DbSet<新聞> 新聞 { get; set; }
        public virtual DbSet<編輯器> 編輯器 { get; set; }
        public virtual DbSet<課程> 課程 { get; set; }
        public virtual DbSet<檔案> 檔案 { get; set; }
        public virtual DbSet<SMS_EMAIL_FAX_LIST> SMS_EMAIL_FAX_LIST { get; set; }
        public virtual DbSet<能源案例> 能源案例 { get; set; }
        public virtual DbSet<研討會報名人員> 研討會報名人員 { get; set; }
        public virtual DbSet<研討會明細檔> 研討會明細檔 { get; set; }
    }
}
