//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAXDetail
    {
        public int FAX_ID { get; set; }
        public int FAX_NO { get; set; }
        public string FAX_TITLE { get; set; }
        public string FAX_TEL { get; set; }
        public string FAX_COMPANY { get; set; }
        public string FAX_NAME { get; set; }
        public string SEND_COMPANY { get; set; }
        public string SEND_NAME { get; set; }
        public int USEDFOR { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public int INSERT_NAME { get; set; }
        public Nullable<bool> IS_SUCCESS { get; set; }
    }
}
