//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSDetail
    {
        public int SMS_ID { get; set; }
        public int SMS_NO { get; set; }
        public string NAME { get; set; }
        public string TEL { get; set; }
        public string MSG_ID { get; set; }
        public string STATUSCODE { get; set; }
        public int USEDFOR { get; set; }
        public int INSERT_NAME { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public Nullable<bool> IS_SUCCESS { get; set; }
        public Nullable<System.DateTime> DLVTIME_RE { get; set; }
        public Nullable<System.DateTime> DONETIME_RE { get; set; }
        public Nullable<int> STATUSCODE_RE { get; set; }
        public string STATUSSTR_RE { get; set; }
        public Nullable<int> STATUSFLAG_RE { get; set; }
        public string STATUSSTRMEMO_RE { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATE_RE { get; set; }
    }
}
