//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSResponseMsg
    {
        public string msg_id { get; set; }
        public string dstaddr { get; set; }
        public System.DateTime dlvtime { get; set; }
        public System.DateTime donetime { get; set; }
        public int statuscode { get; set; }
        public string statusstr { get; set; }
        public Nullable<int> statusFlag { get; set; }
        public System.DateTime receiveDate { get; set; }
        public string statusstrMemo { get; set; }
    }
}
