//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TYBADB : DbContext
    {
        public TYBADB()
            : base("name=TYBADB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DLFILES> DLFILES { get; set; }
        public virtual DbSet<FILEBASE> FILEBASE { get; set; }
        public virtual DbSet<BANNER> BANNER { get; set; }
        public virtual DbSet<EDITOR> EDITOR { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
        public virtual DbSet<RESULT> RESULT { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<OLACT> OLACT { get; set; }
        public virtual DbSet<OLACTGROUP> OLACTGROUP { get; set; }
        public virtual DbSet<APPLY> APPLY { get; set; }
        public virtual DbSet<APPLY_MEMBER> APPLY_MEMBER { get; set; }
        public virtual DbSet<APPLY_NUMBER> APPLY_NUMBER { get; set; }
    }
}
