//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class 人員
    {
        public int 人員代碼 { get; set; }
        public string 帳號 { get; set; }
        public string 密碼 { get; set; }
        public string 姓名 { get; set; }
        public Nullable<int> 單位代碼 { get; set; }
        public bool 停權 { get; set; }
        public string 代碼 { get; set; }
        public string 職稱 { get; set; }
        public string 職務代理人 { get; set; }
        public Nullable<System.DateTime> 到職日 { get; set; }
    }
}
