//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class 出版品主檔
    {
        public int 主索引 { get; set; }
        public int 對應分類索引 { get; set; }
        public System.DateTime 發稿時間 { get; set; }
        public string 發稿人 { get; set; }
        public string 名稱 { get; set; }
        public string 摘要 { get; set; }
        public Nullable<double> 排序 { get; set; }
        public bool 顯示狀態 { get; set; }
        public System.DateTime 建立時間 { get; set; }
        public System.DateTime 更新時間 { get; set; }
        public int 更新人員 { get; set; }
    }
}
