//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class 問卷主檔
    {
        public int 主索引 { get; set; }
        public string 問卷標題 { get; set; }
        public string 問卷描述 { get; set; }
        public System.DateTime 開放時間起始日 { get; set; }
        public System.DateTime 開放時間結束日 { get; set; }
        public bool 是否上架 { get; set; }
        public int 預計發出量 { get; set; }
        public bool 是否需要登入 { get; set; }
        public string 問卷網址 { get; set; }
        public double 排序 { get; set; }
        public System.DateTime 建立日期 { get; set; }
        public int 建立人員 { get; set; }
        public System.DateTime 更新日期 { get; set; }
        public int 更新人員 { get; set; }
    }
}
