//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class 問卷題目檔
    {
        public int 主索引 { get; set; }
        public Nullable<int> 對應問卷索引 { get; set; }
        public Nullable<int> 對應問卷題目類型索引 { get; set; }
        public string 問卷題目內容 { get; set; }
        public System.DateTime 更新日期 { get; set; }
        public int 更新人員 { get; set; }
        public bool 是否必填 { get; set; }
        public double 排序 { get; set; }
    }
}
