//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class 檔案
    {
        public int 主索引 { get; set; }
        public int 對應索引 { get; set; }
        public string 對應名稱 { get; set; }
        public string 檔案模式 { get; set; }
        public string 檔案格式 { get; set; }
        public string 檔案名稱 { get; set; }
        public string 原始檔名 { get; set; }
        public string 檔案路徑 { get; set; }
        public string 檔案虛擬路徑 { get; set; }
        public System.DateTime 更新時間 { get; set; }
        public int 更新人員 { get; set; }
        public System.DateTime 建立時間 { get; set; }
        public int 建立人員 { get; set; }
        public int 排序 { get; set; }
        public Nullable<int> 識別碼 { get; set; }
        public string 傳真檔案路徑 { get; set; }
        public string 傳真檔案名稱 { get; set; }
    }
}
