//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class 研討會明細檔
    {
        public int 主索引 { get; set; }
        public int 對應研討會主索引 { get; set; }
        public string 活動地點 { get; set; }
        public Nullable<System.DateTime> 活動日期起 { get; set; }
        public Nullable<System.DateTime> 活動日期訖 { get; set; }
        public string 活動時間範圍 { get; set; }
        public string 主辦單位 { get; set; }
        public string 協辦單位 { get; set; }
        public string 報名期限_起 { get; set; }
        public string 報名期限_迄 { get; set; }
        public string 聯絡人 { get; set; }
        public string 連絡電話 { get; set; }
        public string 備註 { get; set; }
        public Nullable<int> 活動人數上限 { get; set; }
        public string 活動內容 { get; set; }
        public Nullable<bool> 顯示狀態 { get; set; }
        public Nullable<double> 排序 { get; set; }
        public Nullable<bool> 首頁顯示 { get; set; }
        public Nullable<int> 用戶參加人數限制 { get; set; }
        public Nullable<bool> 收費狀態 { get; set; }
    }
}
