//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class 研討會報名主檔
    {
        public int 主索引 { get; set; }
        public string 用戶編號 { get; set; }
        public string 公司名稱 { get; set; }
        public string 聯絡人姓名 { get; set; }
        public string 聯絡人Email { get; set; }
        public string 聯絡人生日 { get; set; }
        public string 聯絡人手機 { get; set; }
        public string 公司電話 { get; set; }
        public string 公司傳真 { get; set; }
        public string 公司統編 { get; set; }
        public string 統編抬頭 { get; set; }
        public bool 同意條文 { get; set; }
        public Nullable<int> 排序 { get; set; }
        public Nullable<System.DateTime> 更新時間 { get; set; }
    }
}
